language: node_js
node_js:
  - 10
  - 12
  - 14
sudo: false

branches:
  only:
    - develop
    - main

notifications:
  email: false

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run lint
  #- npm test

before_deploy:
  - npm run build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mycv-web
  on:
    branch: master

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run release
