FROM node:14.16.1-alpine

EXPOSE 4200

RUN adduser -S app

ENV HOME=/home/app

COPY package.json $HOME/
RUN chown -R app $HOME/*

USER app
WORKDIR $HOME

RUN rm -rf node_modules package-lock.json
RUN npm cache clean --force && npm cache verify
RUN npm install

USER root
COPY . $HOME/
RUN chown -R app $HOME/*

USER app

RUN npm run build
