version: '3.7'

services:

  example:
    container_name: mycv-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
    networks:
      - docker_default
    command: >
      bash -c "npm run start:dev"
networks:
  docker_default:
    external: false
