version: "3.8"
services:
  client:
    container_name: mycv-web
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "83:80"
    volumes:
      - "/app/node_modules"
      - "./:/app"
