# base image
FROM node:14.17.0-alpine

RUN adduser -S app

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app
RUN chown -R app /app/*

RUN npm install

# add app
USER root

RUN npm install -g @angular/cli@latest

COPY . /app
RUN chown -R app /app/*

# start app
USER app
CMD npm install
CMD ng serve --host 0.0.0.0
