FROM node:14.17.0 as build

WORKDIR /app
COPY package.json /app

RUN rm -rf node_modules package-lock.json
RUN npm cache clean --force && npm cache verify
RUN npm install
RUN npm install @angular/cli

COPY . /app

RUN npm run build

# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
COPY --from=build /app/dist/mycv /usr/share/nginx/html

# Expose port 80
EXPOSE 83
